/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emp.mx.view;

import com.com.mx.dao.DetaProDAO;
import com.emp.mx.bo.DetaProBO;
import com.emp.mx.entity.DetalleProducto;
import javax.swing.JOptionPane;

/**
 *
 * @author Moise
 */
public class FrmDetaPro extends javax.swing.JFrame {

    /**
     * Creates new form FrmDetaPro
     */
    private DetaProBO ebo = new DetaProBO();
    public FrmDetaPro() {
        initComponents();
        listarDeta();
        setTitle("Formulario Detalle productos");
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public void listarDeta(){
        ebo.ListarDeta(tbDeta);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtDetalles = new javax.swing.JTextField();
        txtPRODUCTO_ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInsert1 = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnelimi = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDeta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        txtDetalles.setBackground(new java.awt.Color(255, 255, 255));
        txtDetalles.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtDetalles.setForeground(new java.awt.Color(0, 0, 0));
        txtDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(txtDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        txtPRODUCTO_ID.setBackground(new java.awt.Color(255, 255, 255));
        txtPRODUCTO_ID.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtPRODUCTO_ID.setForeground(new java.awt.Color(0, 0, 0));
        txtPRODUCTO_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRODUCTO_IDActionPerformed(evt);
            }
        });
        jPanel1.add(txtPRODUCTO_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID Ingrediente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Porción:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btnInsert1.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert1.setForeground(new java.awt.Color(0, 0, 0));
        btnInsert1.setText("INSERTAR");
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setForeground(new java.awt.Color(0, 0, 0));
        btnModif.setText("MODIFICAR");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnelimi.setBackground(new java.awt.Color(255, 255, 255));
        btnelimi.setForeground(new java.awt.Color(0, 0, 0));
        btnelimi.setText("ELIMINAR");
        btnelimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelimiActionPerformed(evt);
            }
        });
        jPanel1.add(btnelimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        btnClean.setBackground(new java.awt.Color(255, 255, 255));
        btnClean.setForeground(new java.awt.Color(0, 0, 0));
        btnClean.setText("LIMPIAR");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel1.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        tbDeta.setBackground(new java.awt.Color(255, 255, 255));
        tbDeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDetaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDeta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 590, 270));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Formulario Detalle Producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetallesActionPerformed

    private void txtPRODUCTO_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRODUCTO_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRODUCTO_IDActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
        if(txtPRODUCTO_ID.getText().isEmpty() || txtNombre.getText().isEmpty() || txtDetalles.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            DetalleProducto pro = new DetalleProducto();
            pro.setDETA_PRODUCTO_ID(Integer.parseInt(txtPRODUCTO_ID.getText()));
            pro.setDETA_INGREDIENTE_ID(Integer.parseInt(txtNombre.getText()));
            pro.setPORCION(Integer.parseInt(txtDetalles.getText()));
            String mensaje;
            try {
                mensaje = ebo.agregarDeta(pro);
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                listarDeta();
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInsert1ActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        // TODO add your handling code here:
        if(txtPRODUCTO_ID.getText().isEmpty() || txtNombre.getText().isEmpty() || txtDetalles.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            DetalleProducto pro = new DetalleProducto();
            pro.setDETA_PRODUCTO_ID(Integer.parseInt(txtPRODUCTO_ID.getText()));
            pro.setDETA_INGREDIENTE_ID(Integer.parseInt(txtNombre.getText()));
            pro.setPORCION(Integer.parseInt(txtDetalles.getText()));

            String mensaje;
            try {
                mensaje = ebo.modifiDeta(pro);
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                listarDeta();
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnelimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelimiActionPerformed
        // TODO add your handling code here:
        if(txtPRODUCTO_ID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene El ID a borrar");
        }else{
            String mensaje;
            try {
                mensaje = ebo.eliminarDeta(Integer.parseInt(txtPRODUCTO_ID.getText()),Integer.parseInt(txtNombre.getText()));
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                listarDeta();
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnelimiActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCleanActionPerformed
    public void limpiar(){
        txtPRODUCTO_ID.setText("");
        txtNombre.setText("");
        txtDetalles.setText("");
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tbDetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDetaMouseClicked
        // TODO add your handling code here:
        int seleccion = tbDeta.rowAtPoint(evt.getPoint());
        txtPRODUCTO_ID.setText((String) tbDeta.getValueAt(seleccion, 0));
        txtNombre.setText((String) tbDeta.getValueAt(seleccion, 1));
        txtDetalles.setText((String) tbDeta.getValueAt(seleccion, 2));
    }//GEN-LAST:event_tbDetaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDetaPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnelimi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDeta;
    private javax.swing.JTextField txtDetalles;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPRODUCTO_ID;
    // End of variables declaration//GEN-END:variables
}
