/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emp.mx.view;

import com.emp.mx.bo.EmpleadoBO;
import com.emp.mx.entity.empleado;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Moise
 */
public class FrmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleado
     */
    private EmpleadoBO ebo = new EmpleadoBO();
    
    public FrmEmpleado() {
        initComponents();
        listarEmpleado();
        setTitle("Formulario Empleado");
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public void listarEmpleado(){
        ebo.ListarEmple(tbEmpleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEMPLEADO_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDomi = new javax.swing.JTextField();
        txtSuc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnelimi = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(428, 712));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtEMPLEADO_ID.setBackground(new java.awt.Color(255, 255, 255));
        txtEMPLEADO_ID.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtEMPLEADO_ID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtEMPLEADO_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Formulario Empleado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido Paterno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtApellidoP.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoP.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido Materno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtApellidoM.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoM.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Lada:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtLada.setBackground(new java.awt.Color(255, 255, 255));
        txtLada.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtLada.setForeground(new java.awt.Color(0, 0, 0));
        txtLada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadaActionPerformed(evt);
            }
        });
        jPanel1.add(txtLada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Telefono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 170, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Correo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 170, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("RFC:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtRFC.setBackground(new java.awt.Color(255, 255, 255));
        txtRFC.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 170, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ROL:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Sucursal:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtRol.setBackground(new java.awt.Color(255, 255, 255));
        txtRol.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtRol.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 170, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Domicilio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        txtDomi.setBackground(new java.awt.Color(255, 255, 255));
        txtDomi.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtDomi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtDomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 170, -1));

        txtSuc.setBackground(new java.awt.Color(255, 255, 255));
        txtSuc.setForeground(new java.awt.Color(0, 0, 0));
        txtSuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        txtSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSucActionPerformed(evt);
            }
        });
        jPanel1.add(txtSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, -1));

        tbEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 590, 270));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        btnelimi.setBackground(new java.awt.Color(255, 255, 255));
        btnelimi.setForeground(new java.awt.Color(0, 0, 0));
        btnelimi.setText("ELIMINAR");
        btnelimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelimiActionPerformed(evt);
            }
        });
        jPanel1.add(btnelimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setForeground(new java.awt.Color(0, 0, 0));
        btnModif.setText("MODIFICAR");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setForeground(new java.awt.Color(0, 0, 0));
        btnInsert.setText("INSERTAR");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnClean.setBackground(new java.awt.Color(255, 255, 255));
        btnClean.setForeground(new java.awt.Color(0, 0, 0));
        btnClean.setText("LIMPIAR");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel1.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSucActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnelimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelimiActionPerformed
        // TODO add your handling code here:
        if(txtEMPLEADO_ID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene El ID a borrar");
        }else{
            String mensaje;
            try {
                mensaje = ebo.eliminarEmple(Integer.parseInt(txtEMPLEADO_ID.getText()));
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                listarEmpleado();
            } catch (SQLException ex) {
                Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }
    }//GEN-LAST:event_btnelimiActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        // TODO add your handling code here:
        if(txtEMPLEADO_ID.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApellidoP.getText().isEmpty() || txtApellidoM.getText().isEmpty()
                || txtLada.getText().isEmpty() || txtTelefono.getText().isEmpty()|| txtRFC.getText().isEmpty() || txtRol.getText().isEmpty()
                || txtDomi.getText().isEmpty() || txtCorreo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            empleado emp = new empleado();
            emp.setEMPLEADO_ID(Integer.parseInt(txtEMPLEADO_ID.getText()));
            emp.setNAME_EMPLEADO(txtNombre.getText());
            emp.setAPELLIDOP_EMPLEADO(txtApellidoP.getText());
            emp.setAPELLIDOM_EMPLEADO(txtApellidoM.getText());
            emp.setLADA_EMPLEADO(Integer.parseInt(txtLada.getText()));
            emp.setTEL_EMPLEADO(Integer.parseInt(txtTelefono.getText()));
            emp.setCORREO_EMPLEADO(txtCorreo.getText());
            emp.setRFC_EMPLEADO(txtRFC.getText());
            emp.setROL_EMPLEADO(txtRol.getText());
            emp.setEMPLEADO_SUCURSAL(Integer.parseInt((String) txtSuc.getSelectedItem()));
            //emp.setEMPLEADO_SUCURSAL(2); 
            emp.setEMPLEADO_DOMICILIO(Integer.parseInt(txtDomi.getText()));
            String mensaje;
            try {
                mensaje = ebo.modifiEmple(emp);
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                listarEmpleado();
            } catch (SQLException ex) {
                Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }   
        
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        if(txtEMPLEADO_ID.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApellidoP.getText().isEmpty() || txtApellidoM.getText().isEmpty()
                || txtLada.getText().isEmpty() || txtTelefono.getText().isEmpty()|| txtRFC.getText().isEmpty() || txtRol.getText().isEmpty()
                || txtDomi.getText().isEmpty() || txtCorreo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            empleado emp = new empleado();
            emp.setEMPLEADO_ID(Integer.parseInt(txtEMPLEADO_ID.getText()));
            emp.setNAME_EMPLEADO(txtNombre.getText());
            emp.setAPELLIDOP_EMPLEADO(txtApellidoP.getText());
            emp.setAPELLIDOM_EMPLEADO(txtApellidoM.getText());
            emp.setLADA_EMPLEADO(Integer.parseInt(txtLada.getText()));
            emp.setTEL_EMPLEADO(Integer.parseInt(txtTelefono.getText()));
            emp.setCORREO_EMPLEADO(txtCorreo.getText());
            emp.setRFC_EMPLEADO(txtRFC.getText());
            emp.setROL_EMPLEADO(txtRol.getText());
            emp.setEMPLEADO_SUCURSAL(Integer.parseInt((String) txtSuc.getSelectedItem()));
            //emp.setEMPLEADO_SUCURSAL(2); 
            emp.setEMPLEADO_DOMICILIO(Integer.parseInt(txtDomi.getText()));
            String mensaje;
            try {
                mensaje = ebo.agregarEmple(emp);
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                listarEmpleado();
            } catch (SQLException ex) {
                Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCleanActionPerformed
    public void limpiar(){
        txtEMPLEADO_ID.setText("");
        txtNombre.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtLada.setText("");
        txtTelefono.setText("");
        txtRFC.setText("");
        txtCorreo.setText("");
        txtRol.setText("");
        txtDomi.setText("");
        txtSuc.setSelectedItem("1");
    }
    private void txtLadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void tbEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadoMouseClicked
        // TODO add your handling code here:
        int seleccion = tbEmpleado.rowAtPoint(evt.getPoint());
        txtEMPLEADO_ID.setText((String) tbEmpleado.getValueAt(seleccion, 0));
        txtNombre.setText((String) tbEmpleado.getValueAt(seleccion, 1));
        txtApellidoP.setText((String) tbEmpleado.getValueAt(seleccion, 2));
        txtApellidoM.setText((String) tbEmpleado.getValueAt(seleccion, 3));
        txtLada.setText((String) tbEmpleado.getValueAt(seleccion, 4));
        txtTelefono.setText((String) tbEmpleado.getValueAt(seleccion, 5));
        txtRFC.setText((String) tbEmpleado.getValueAt(seleccion, 6));
        txtCorreo.setText((String) tbEmpleado.getValueAt(seleccion, 7));
        txtRol.setText((String) tbEmpleado.getValueAt(seleccion,8));
        txtSuc.setSelectedItem(tbEmpleado.getValueAt(seleccion, 9));
        txtDomi.setText((String) tbEmpleado.getValueAt(seleccion, 10));
        
    }//GEN-LAST:event_tbEmpleadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnelimi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmpleado;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDomi;
    private javax.swing.JTextField txtEMPLEADO_ID;
    private javax.swing.JTextField txtLada;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtRol;
    private javax.swing.JComboBox<String> txtSuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
