/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emp.mx.view;

import com.com.mx.dao.ingreDAO;
import com.emp.mx.bo.IngredientesBO;
import javax.swing.JOptionPane;
import com.emp.mx.entity.Ingredientes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moise
 */
public class FrmIngredi extends javax.swing.JFrame {

    /**
     * Creates new form FrmIngredi
     */
    private IngredientesBO ebo = new IngredientesBO();
    
    public FrmIngredi() {
        initComponents();
        ListarIngre();
        setTitle("Formulario Ingredientes");
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public void ListarIngre(){
        ebo.ListarIngre(tbIngrediente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtINGRE_ID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jNombre_Ingre = new javax.swing.JLabel();
        jID = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnelimi = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngrediente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Formulario Ingredientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        txtINGRE_ID.setBackground(new java.awt.Color(255, 255, 255));
        txtINGRE_ID.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtINGRE_ID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtINGRE_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, -1));

        jNombre_Ingre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jNombre_Ingre.setForeground(new java.awt.Color(0, 0, 0));
        jNombre_Ingre.setText("Nombre Ingrediente:");
        jPanel1.add(jNombre_Ingre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jID.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jID.setForeground(new java.awt.Color(0, 0, 0));
        jID.setText("ID:");
        jPanel1.add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setForeground(new java.awt.Color(0, 0, 0));
        btnInsert.setText("INSERTAR");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 90, 30));

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setForeground(new java.awt.Color(0, 0, 0));
        btnModif.setText("MODIFICAR");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, 30));

        btnelimi.setBackground(new java.awt.Color(255, 255, 255));
        btnelimi.setForeground(new java.awt.Color(0, 0, 0));
        btnelimi.setText("ELIMINAR");
        btnelimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelimiActionPerformed(evt);
            }
        });
        jPanel1.add(btnelimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 90, 30));

        btnClean.setBackground(new java.awt.Color(255, 255, 255));
        btnClean.setForeground(new java.awt.Color(0, 0, 0));
        btnClean.setText("LIMPIAR");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel1.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 90, 30));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 90, 30));

        tbIngrediente.setBackground(new java.awt.Color(255, 255, 255));
        tbIngrediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIngredienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIngrediente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 450, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if(txtINGRE_ID.getText().isEmpty() || txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
        else{
            Ingredientes ingre = new Ingredientes();
            ingre.setID_INGREDIENTES(Integer.parseInt(txtINGRE_ID.getText()));
            ingre.setNAME_INGREDIENTE(txtNombre.getText());
            String mensaje;
            try {
                mensaje = ebo.agregarIngre(ingre);
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                ListarIngre();
            } catch (SQLException ex){
                Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        // TODO add your handling code here:
        if(txtINGRE_ID.getText().isEmpty() || txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
        else{
            Ingredientes ingre = new Ingredientes();
            ingre.setID_INGREDIENTES(Integer.parseInt(txtINGRE_ID.getText()));
            ingre.setNAME_INGREDIENTE(txtNombre.getText());
            String mensaje;
            try {
                mensaje = ebo.modifiIngre(ingre);
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                ListarIngre();
            } catch (SQLException ex){
                Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnModifActionPerformed

    private void btnelimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelimiActionPerformed
        // TODO add your handling code here:
        if(txtINGRE_ID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
        else{
            Ingredientes ingre = new Ingredientes();
            ingre.setID_INGREDIENTES(Integer.parseInt(txtINGRE_ID.getText()));
            ingre.setNAME_INGREDIENTE(txtNombre.getText());
            String mensaje;
            try {
                mensaje = ebo.eliminarIngre(Integer.parseInt(txtINGRE_ID.getText()));
                JOptionPane.showMessageDialog(null,mensaje);
                limpiar();
                ListarIngre();
            } catch (SQLException ex){
                Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnelimiActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCleanActionPerformed
    public void limpiar(){
        txtINGRE_ID.setText("");
        txtNombre.setText("");
        
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tbIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIngredienteMouseClicked
        // TODO add your handling code here:
        int seleccion = tbIngrediente.rowAtPoint(evt.getPoint());
        txtINGRE_ID.setText((String) tbIngrediente.getValueAt(seleccion, 0));
        txtNombre.setText((String) tbIngrediente.getValueAt(seleccion, 1));
        

    }//GEN-LAST:event_tbIngredienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIngredi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIngredi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIngredi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIngredi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIngredi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnelimi;
    private javax.swing.JLabel jID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNombre_Ingre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbIngrediente;
    private javax.swing.JTextField txtINGRE_ID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
