/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emp.mx.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moise
 */
public class viewsFrm extends javax.swing.JFrame {

    /**
     * Creates new form viewsFrm
     */
    public viewsFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jClientes = new javax.swing.JButton();
        PedidosSuc = new javax.swing.JButton();
        jDirecciones = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jIngredientes = new javax.swing.JButton();
        jProductos = new javax.swing.JButton();
        jPedidos = new javax.swing.JButton();
        jPedidos1 = new javax.swing.JButton();
        jDirecciones1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jEmpleados1 = new javax.swing.JButton();
        CantidadMes = new javax.swing.JButton();
        EmpPed = new javax.swing.JButton();
        IngreProd = new javax.swing.JButton();
        ProduVend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CONSULTAS POPULARES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 240, 36));

        jClientes.setBackground(new java.awt.Color(246, 90, 130));
        jClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jClientes.setForeground(new java.awt.Color(0, 0, 0));
        jClientes.setText("Clientes");
        jClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 110, 40));

        PedidosSuc.setBackground(new java.awt.Color(246, 90, 130));
        PedidosSuc.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PedidosSuc.setForeground(new java.awt.Color(0, 0, 0));
        PedidosSuc.setText("Pedidos Sucursal");
        PedidosSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosSucActionPerformed(evt);
            }
        });
        jPanel1.add(PedidosSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 40));

        jDirecciones.setBackground(new java.awt.Color(246, 90, 130));
        jDirecciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jDirecciones.setForeground(new java.awt.Color(0, 0, 0));
        jDirecciones.setText("Direcciones");
        jDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDireccionesActionPerformed(evt);
            }
        });
        jPanel1.add(jDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, 40));

        jSalir.setBackground(new java.awt.Color(246, 90, 130));
        jSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(0, 0, 0));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 110, 40));

        jIngredientes.setBackground(new java.awt.Color(246, 90, 130));
        jIngredientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jIngredientes.setForeground(new java.awt.Color(0, 0, 0));
        jIngredientes.setText("Ingredientes");
        jIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngredientesActionPerformed(evt);
            }
        });
        jPanel1.add(jIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 110, 40));

        jProductos.setBackground(new java.awt.Color(246, 90, 130));
        jProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jProductos.setForeground(new java.awt.Color(0, 0, 0));
        jProductos.setText("Productos");
        jProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductosActionPerformed(evt);
            }
        });
        jPanel1.add(jProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 120, 40));

        jPedidos.setBackground(new java.awt.Color(246, 90, 130));
        jPedidos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPedidos.setForeground(new java.awt.Color(0, 0, 0));
        jPedidos.setText("Pedidos");
        jPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(jPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 110, 40));

        jPedidos1.setBackground(new java.awt.Color(246, 90, 130));
        jPedidos1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPedidos1.setForeground(new java.awt.Color(0, 0, 0));
        jPedidos1.setText("Sucursales");
        jPedidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPedidos1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPedidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 120, 40));

        jDirecciones1.setBackground(new java.awt.Color(246, 90, 130));
        jDirecciones1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jDirecciones1.setForeground(new java.awt.Color(0, 0, 0));
        jDirecciones1.setText("Detalles Ingredientes");
        jDirecciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDirecciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(jDirecciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 170, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ACCESO AL SISTEMA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 187, 36));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MODIFICACIONES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 187, 36));

        jEmpleados1.setBackground(new java.awt.Color(246, 90, 130));
        jEmpleados1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jEmpleados1.setForeground(new java.awt.Color(0, 0, 0));
        jEmpleados1.setText("Empleados");
        jEmpleados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpleados1ActionPerformed(evt);
            }
        });
        jPanel1.add(jEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 110, 40));

        CantidadMes.setBackground(new java.awt.Color(246, 90, 130));
        CantidadMes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CantidadMes.setForeground(new java.awt.Color(0, 0, 0));
        CantidadMes.setText("Cantidad Pedidos");
        CantidadMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadMesActionPerformed(evt);
            }
        });
        jPanel1.add(CantidadMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 190, 40));

        EmpPed.setBackground(new java.awt.Color(246, 90, 130));
        EmpPed.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        EmpPed.setForeground(new java.awt.Color(0, 0, 0));
        EmpPed.setText("Empleado Pedidos");
        EmpPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPedActionPerformed(evt);
            }
        });
        jPanel1.add(EmpPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 40));

        IngreProd.setBackground(new java.awt.Color(246, 90, 130));
        IngreProd.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        IngreProd.setForeground(new java.awt.Color(0, 0, 0));
        IngreProd.setText("Ingredientes Producto");
        IngreProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreProdActionPerformed(evt);
            }
        });
        jPanel1.add(IngreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, 40));

        ProduVend.setBackground(new java.awt.Color(246, 90, 130));
        ProduVend.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ProduVend.setForeground(new java.awt.Color(0, 0, 0));
        ProduVend.setText("Más Vendido");
        ProduVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduVendActionPerformed(evt);
            }
        });
        jPanel1.add(ProduVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientesActionPerformed
        // TODO add your handling code here:
        FrmCliente mf = new FrmCliente();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jClientesActionPerformed

    private void PedidosSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosSucActionPerformed
        // TODO add your handling code here:
        FrmSel1 mf = new FrmSel1();
        mf.setVisible(true);            
        dispose();  
    }//GEN-LAST:event_PedidosSucActionPerformed

    private void jDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDireccionesActionPerformed
        // TODO add your handling code here:
        FrmDire mf = new FrmDire();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jDireccionesActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngredientesActionPerformed
        // TODO add your handling code here:
        FrmIngredi mf = new FrmIngredi();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jIngredientesActionPerformed

    private void jProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductosActionPerformed
        // TODO add your handling code here:
        FrmProducto mf = new FrmProducto();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jProductosActionPerformed

    private void jPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPedidosActionPerformed
        // TODO add your handling code here:
        FrmPedido mf = new FrmPedido();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jPedidosActionPerformed

    private void jPedidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPedidos1ActionPerformed
        // TODO add your handling code here:
        FrmSuc mf = new FrmSuc();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jPedidos1ActionPerformed

    private void jDirecciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDirecciones1ActionPerformed
        // TODO add your handling code here:
        FrmDetaPro mf = new FrmDetaPro();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_jDirecciones1ActionPerformed

    private void jEmpleados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpleados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmpleados1ActionPerformed

    private void CantidadMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadMesActionPerformed
        // TODO add your handling code here:
        FrmSel5 mf = null;
        try {
            mf = new FrmSel5();
        } catch (SQLException ex) {
            Logger.getLogger(viewsFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_CantidadMesActionPerformed

    private void EmpPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPedActionPerformed
        // TODO add your handling code here:
        FrmSel2 mf = new FrmSel2();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_EmpPedActionPerformed

    private void IngreProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreProdActionPerformed
        // TODO add your handling code here:
        FrmSelect3 mf = null;
        try {
            mf = new FrmSelect3();
        } catch (SQLException ex) {
            Logger.getLogger(viewsFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_IngreProdActionPerformed

    private void ProduVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduVendActionPerformed
        // TODO add your handling code here:
        FrmSel4 mf = new FrmSel4();
        mf.setVisible(true);            
        dispose();
    }//GEN-LAST:event_ProduVendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewsFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CantidadMes;
    private javax.swing.JButton EmpPed;
    private javax.swing.JButton IngreProd;
    private javax.swing.JButton PedidosSuc;
    private javax.swing.JButton ProduVend;
    private javax.swing.JButton jClientes;
    private javax.swing.JButton jDirecciones;
    private javax.swing.JButton jDirecciones1;
    private javax.swing.JButton jEmpleados1;
    private javax.swing.JButton jIngredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPedidos;
    private javax.swing.JButton jPedidos1;
    private javax.swing.JButton jProductos;
    private javax.swing.JButton jSalir;
    // End of variables declaration//GEN-END:variables
}
